plugins {
    id 'java'
}

group = 'io.github.velocitytoolbox'
version = '0.1.0-SNAPSHOT'

repositories {
    maven {
        name = 'papermc'
        url = uri('https://repo.papermc.io/repository/maven-public/')
    }
}

dependencies {
    compileOnly 'com.velocitypowered:velocity-api:4.1.0-SNAPSHOT'
    annotationProcessor 'com.velocitypowered:velocity-api:4.1.0-SNAPSHOT'
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

tasks.withType(JavaCompile).configureEach {
    options.release = 25
    options.encoding = 'UTF-8'
    options.compilerArgs.add('-parameters')
}

tasks.withType(Jar).configureEach {
    archiveBaseName = 'VelocityToolbox'
}
